baseURL = 'https://airflow.atwish.org/'
languageCode = 'en-us'
title = 'Apache Airflow Documentation - At Your Wish'
theme = ['hugo-theme-relearn-main']

sectionPagesMenu = 'main'

[params]
  Description = "Comprehensive Apache Airflow Documentation - As You Wished, At Your Wish."

  [[params.themeVariant]]
    identifier = 'zen-light'

  [[params.meta]]
    description = "Learn Apache Airflow with structured documentation, tutorials, and best practices. Your go-to source for mastering workflow automation!"
    Author = "Shantanu Khond"
    keywords = "Apache Airflow, Airflow Documentation, Workflow Automation, Data Pipelines, DAGs, Task Scheduling"
    robots = "index, follow"

[markup.goldmark.parser.attribute]
block = true # default is false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.8

[menu]
  [[menu.shortcuts]]
    identifier = 'ds'
    name = "<i class='fa-fw fab fa-github'></i> GitHub Profile"
    url = 'https://github.com/shantanukhond'
    weight = 10

  [[menu.shortcuts]]
    name = "<i class='fa-fw fas fa-play'></i> YouTube"
    url = 'https://youtube.com/@shantanuKhond/'
    weight = 11

  [[menu.shortcuts]]
    identifier = 'hugodoc'
    name = "<i class='fa-fw fas fa-usd'></i> Sponsor Us"
    url = 'https://www.buymeacoffee.com/shantanukhond'
    weight = 20

  [[menu.shortcuts]]
    name = "<i class='fa-fw fas fa-bullhorn'></i> Privacy Policy"
    url = '/privacy-policy.html'
    weight = 30

[services]
  [services.googleAnalytics]
    id = "G-42VH65VMD6"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
